// معاينات v0.18 «مركز الإدارة» للمجلد على الجهاز وللرد
import { chromium } from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
import path from 'node:path';
import fs from 'node:fs';
const file = 'file://' + path.resolve('dist/index.html');
const OUT = process.argv[2] || '/mnt/user-data/outputs/v18'; fs.mkdirSync(OUT, { recursive: true });
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
const p = await ctx.newPage();
await p.goto(file + '#/home', { waitUntil: 'load' }); await p.waitForTimeout(500);
const become = async (who, hash, vp, lang = 'ar') => {
  if (vp) await p.setViewportSize(vp);
  await p.evaluate(({ who, lang }) => { const s = JSON.parse(localStorage.getItem('usp-portal-v1')); s.settings.lang = lang; if (who === 'admin') { s.settings.persona = 'admin'; s.settings.actAs = undefined; } else { const w = s.people.find((x) => x.id === who); s.settings.persona = w.persona; s.settings.actAs = who; } localStorage.setItem('usp-portal-v1', JSON.stringify(s)); }, { who, lang });
  await p.goto(file + hash); await p.reload({ waitUntil: 'load' }); await p.waitForTimeout(1400);
};
const shot = (name, opts = {}) => p.screenshot({ path: `${OUT}/${name}.png`, ...opts });
const clickTab = async (name) => { const seg = p.locator('.dzs-main .segmented').first(); const inDz = await seg.count(); await (inDz ? seg.locator('button', { hasText: name }).first() : p.getByRole('button', { name }).first()).click(); await p.waitForTimeout(600); };
await become('admin', '#/admin');
await shot('معاينة v0.18 — صفحة الإدارة: يحتاجك والسياسات والطلبات المتأخرة والأرقام والبنية (حاسوب)', { fullPage: true });
await p.goto(file + '#/admin/policy'); await p.waitForTimeout(1200);
await shot('معاينة v0.18 — شريط أقسام الإدارة على مركز سياسة الإجازات و«أخطأت في إصدار سارٍ؟» مطويّاً (حاسوب)');
await p.goto(file + '#/admin/designer'); await p.waitForTimeout(1200);
await shot('معاينة v0.18 — دليل المصمّم مطويّاً بالمجال على الحاسوب');
await clickTab(/^القوالب/); await p.locator('.dz-tpl-preview').first().click(); await p.waitForTimeout(1000);
await shot('معاينة v0.18 — معاينة القالب قبل استعماله: شاشة الموظف والحقول والمسار والمخرجات (حاسوب)');
await p.keyboard.press('Escape'); await p.waitForTimeout(400);
await p.goto(file + '#/admin/designer/svc/DC-01'); await p.waitForTimeout(1200); await clickTab(/^المخرجات/); await p.waitForTimeout(600);
await shot('معاينة v0.18 — المصمّم: لسان المخرجات يعرض المستند نفسه كما سيصدر قبل الحفظ (حاسوب)');
await become('admin', '#/admin', { width: 1440, height: 900 }, 'en');
await shot('معاينة v0.18 — Administration page in English (desktop)', { fullPage: true });
await become('admin', '#/admin', { width: 390, height: 844 }, 'ar');
await shot('معاينة v0.18 — صفحة الإدارة (هاتف)', { fullPage: true });
await p.goto(file + '#/admin/designer/svc/DC-01'); await p.waitForTimeout(1200); await clickTab(/^المخرجات/); await p.locator('.dz-doc-preview').first().click(); await p.waitForTimeout(1000);
await shot('معاينة v0.18 — معاينة المستند في لوح على الهاتف');
await p.keyboard.press('Escape'); await p.waitForTimeout(300);
await p.goto(file + '#/admin/designer'); await p.waitForTimeout(1000); await clickTab(/^القوالب/); await p.locator('.dz-tpl-preview').first().click(); await p.waitForTimeout(1000);
await shot('معاينة v0.18 — معاينة القالب على الهاتف');
await b.close();
console.log('previews ok');
